config/routes.rb
Rails.application.routes.draw do
  root "pagina_inicial#index"
  get 'pagina_inicial/index'
  get 'criar_conta/index'
  post 'criar_conta/new'
  get 'criar_conta/:id', to: 'criar_conta#show'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/agencias.rb
class Agencias < ApplicationRecord
  has_many :contas
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  has_many :contas
end

app/models/contas.rb
class Contas < ApplicationRecord
  belongs_to :cliente, optional: true
  belongs_to :agencias, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/criar_conta_controller.rb
class CriarContaController < ApplicationController
  def index

  end

  def new
    data = params[:clientes]

    @cliete = Cliente.new(
      nome: "#{data[:primeiro_nome]} #{data[:segundo_nome]}",
      cpf: data[:cpf],
      telefone: data[:telefone],
      email: data[:email],
      endereco: "#{data[:endereco]} - #{data[:cep]}, #{data[:cidade]}, #{data[:estado]}"
    )


    agencia = Agencias.find_by(num_agencia: get_agencia(data[:cidade]))
    if @cliete.save
      @conta = Contas.new(numero: rand(10000..50000), saldo: 0.0, data_abertura: DateTime.current.to_date, clientes_id: @cliete.id, agencias_id: agencia.id)
      if @conta.save
        redirect_to controller: :criar_conta, action: :show, id: @conta.id
      end
    end
  end

  def show
    @cliete = Cliente.find(params[:id])
    @conta = Contas.find_by(clientes_id: @cliete.id)
    @agencia = Agencias.find(@conta.agencias_id)

  end

  private
  def get_agencia(cidade)
    num_agencias = {"Goiania": 1234,
     "Aparecida de Goiania": 5678,
     "Brasilia": 9876
    }
    num_agencias[:"#{cidade}"]
  end
end

app/controllers/pagina_inicial_controller.rb
class PaginaInicialController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/criar_conta_helper.rb
module CriarContaHelper
end

app/helpers/pagina_inicial_helper.rb
module PaginaInicialHelper
end

app/views/criar_conta/index.html.erb
<div class="container">
  <main>
    <div class="py-5 text-center" href="<% pagina_inicial_index_path %>">
      <%= link_to root_path do %>
        <img class="d-block mx-auto mb-4" src=<%= image_path("bank-logo.png") %> alt="" width="160" height="80">
    <% end %>
      <h2>Nova Conta Bancária</h2>
      <p class="lead">Preencha o formulário para abrir uma nova conta.</p>
    </div>

    <div class="row g-5">
      <div class="col-md-5 col-lg-4 order-md-last">
        <div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
          <div class="bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
            <div class="my-3 p-3">
              <h2 class="display-5">Simples e rápido</h2>
              <p class="lead">Nunca foi tão fácil ter uma conta bancária.</p>
            </div>
            <div class="bg-body shadow-sm mx-auto" style="width: 80%; height: 250px; border-radius: 21px 21px 0 0;"></div>
          </div>
        </div>
      </div>

      <div class="col-md-7 col-lg-8">
        <h4 class="mb-3">Dados pessoais</h4>
        <%= form_for :clientes, url: criar_conta_new_path, class: "needs-validation row g-3" do |form| %>
          <div class="col-sm-6">
            <%= form.label "Primeiro nome", class: "form-label" %>
            <%= form.text_field "primeiro_nome", class: "form-control", required: true %>
          </div>
          <div class="col-sm-6">
            <%= form.label "Segundo nome", class: "form-label" %>
            <%= form.text_field "segundo_nome", class: "form-control", required: true %>
          </div>

          <div class="col-12">
            <%= form.label "Cpf", class: "form-label" %>
            <%= form.number_field "cpf", class: "form-control", placeholder: "000.000.000-00", required: true %>
          </div>

          <div class="col-6">
            <%= form.label "Email", class: "form-label" %>
            <%= form.text_field "email", class: "form-control", placeholder: "you@example.com", required: true %>
          </div>

          <div class="col-6">
            <%= form.label "Telefone", class: "form-label" %>
            <%= form.number_field "telefone", class: "form-control", placeholder: "(99) 9 9999-9999", required: true %>
          </div>

          <div class="col-12">
            <%= form.label "Endereco", class: "form-label" %>
            <%= form.text_field "endereco", class: "form-control", placeholder: "Apartment or suite" %>
          </div>
          <div class="col-4">
            <%= form.label "Cidade", class: "form-label" %>
            <%= form.select "cidade", ["Goiania", "Aparecida de Goiania", "Brasilia"], { :include_blank => 'Escolha cidade' }, { class: "form-select", required: true } %>
          </div>
          <div class="col-4">
            <%= form.label "Estado", class: "form-label" %>
            <%= form.select "estado", ["GO", "DF"], { :include_blank => 'Escolha estado' }, { class: "form-select", required: true } %>
          </div>

          <div class="col-md-3">
            <%= form.label "CEP", class: "form-label" %>
            <%= form.number_field "cep", class: "form-control", placeholder: "00000-000" %>
          </div>
          <hr class="my-4">
          <%= form.submit "Abrir conta", class: "w-100 btn btn-primary btn-lg"%>
        <% end %>
      </div>
    </div>
  </main>

  <footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1">&copy; 2017–2022 PAS Simple Bank</p>
    <ul class="list-inline">
      <li class="list-inline-item"><a href="#">Privacy</a></li>
      <li class="list-inline-item"><a href="#">Terms</a></li>
      <li class="list-inline-item"><a href="#">Support</a></li>
    </ul>
  </footer>
</div>

app/views/criar_conta/show.html.erb
<div class="container py-3">
  <header class="d-flex justify-content-center py-3">
    <ul class="nav nav-pills">
      <li class="nav-item"><a href="/" class="nav-link active" aria-current="page">Inicio</a></li>
      <li class="nav-item"><a href="#" class="nav-link">Sobre Nós</a></li>
      <li class="nav-item"><a href="#" class="nav-link">Suporte</a></li>
      <li class="nav-item"><a href="#" class="nav-link">FAQs</a></li>
    </ul>
  </header>

  <hr class="my-4">

  <main>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
      <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
          <div class="card-header py-3">
            <h4 class="my-0 fw-normal">Conta Corrente</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">R$0<small class="text-muted fw-light">,00</small></h1>
            <button type="button" class="w-100 btn btn-lg btn-outline-primary">Depósitar</button>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
          <div class="card-header py-3">
            <h4 class="my-0 fw-normal">Conta Poupança</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">R$0<small class="text-muted fw-light">,00</small></h1>
            <button type="button" class="w-100 btn btn-lg btn-primary">Depósitar</button>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm border-primary">
          <div class="card-header py-3 text-white bg-primary border-primary">
            <h4 class="my-0 fw-normal">Conta Salário</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">R$0<small class="text-muted fw-light">,00</small></h1>
            <button type="button" class="w-100 btn btn-lg btn-primary">Depósitar</button>
          </div>
        </div>
      </div>
    </div>

    <h2 class="display-6 text-center mb-4">Seus dados</h2>

    <div class="table-responsive">
      <table class="table text-center">
        <thead>
        <tr>
          <th style="width: 34%;"></th>
          <th style="width: 22%;"></th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <th scope="row" class="text-start">Agência</th>
          <td><%= @agencia.num_agencia  %></td>
        </tr>
        <tr>
          <th scope="row" class="text-start">Conta</th>
          <td><%= @conta.numero %></td>
        </tr>
        </tbody>

        <tbody>
        <tr>
          <th scope="row" class="text-start">Data Abertura</th>
          <td><%= @conta.data_abertura %></td>
        </tr>
        <tr>
          <th scope="row" class="text-start">Endereço Agência</th>
          <td><%= @agencia.endereco  %></td>
        </tr>
        </tbody>
      </table>
    </div>
  </main>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PadroesArqSoftwareMvc</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</head>

<body>
<div class="container">
  <div class="row">
    <div class="col">
      <%= yield %>
    </div>
  </div>
</div>
</body>
</html>

app/views/pagina_inicial/index.html.erb
<!-- inside app/views/home/index.html.erb -->
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.84.0">
  <title>Heroes · Bootstrap v5.0</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/heroes/">


  <!-- Bootstrap core CSS -->
  <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

  <style>
      .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
      }

      @media (min-width: 768px) {
          .bd-placeholder-img-lg {
              font-size: 3.5rem;
          }
      }
  </style>
  <!-- Custom styles for this template -->
  <link href="heroes.css" rel="stylesheet">
</head>

<main>
  <div class="container">
    <header class="d-flex justify-content-center py-3">
      <ul class="nav nav-pills">
        <li class="nav-item"><a href="#" class="nav-link active" aria-current="page">Inicio</a></li>
        <li class="nav-item"><a href="#" class="nav-link">Sobre Nós</a></li>
        <li class="nav-item"><a href="#" class="nav-link">Suporte</a></li>
        <li class="nav-item"><a href="#" class="nav-link">FAQs</a></li>
      </ul>
    </header>
  </div>
  <div class="container my-5">
    <img class="d-block mx-auto mb-4" src=<%= image_path("bank-logo.png") %> alt="#" width="400" height="200">
    <div class="row p-4 pb-0 pe-lg-0 pt-lg-5 align-items-center rounded-3 border shadow-lg">
      <div class="col-lg-7 p-3 p-lg-5 pt-lg-3">
        <h1 class="display-4 fw-bold lh-1">PAS Simple Bank</h1>
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit. In euismod bibendum erat, eget lacinia
          leo scelerisque ac.</p>
        <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4 mb-lg-3">
          <div>
            <%= link_to 'Abrir uma conta', criar_conta_index_path, :class => "btn btn-primary btn-lg px-4 me-md-2 fw-bold"%>
          </div>
          <button type="button" class="btn btn-outline-secondary btn-lg px-4">Entrar na sua conta</button>
        </div>
      </div>
      <div class="col-lg-4 offset-lg-1 p-0 overflow-hidden shadow-lg">
        <img class="rounded-lg-3" src=<%= image_path("bank-builder.png") %> alt="" width="720">
      </div>
    </div>
  </div>
</main>


<!--<script src="../assets/dist/js/bootstrap.bundle.min.js"></script>-->